<a href="https://colab.research.google.com/github/hlnynhi/Python-nang-cao/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài tập chương 8


1.

In [1]:
kingdoms = ['Bacteria', 'Protozoa', 'Chromista', 'Plantae', 'Fungi', 'Animalia']
kingdoms[0]

'Bacteria'

In [2]:
kingdoms[5]

'Animalia'

In [3]:
kingdoms[:3]

['Bacteria', 'Protozoa', 'Chromista']

In [4]:
kingdoms[2:5]

['Chromista', 'Plantae', 'Fungi']

In [5]:
kingdoms[4:]

['Fungi', 'Animalia']

In [6]:
kingdoms[1:0]

[]

2.

In [7]:
kingdoms[-6]

'Bacteria'

In [8]:
kingdoms[-1]

'Animalia'

In [9]:
kingdoms[-6:-3]

['Bacteria', 'Protozoa', 'Chromista']

In [10]:
kingdoms[-4:-1]

['Chromista', 'Plantae', 'Fungi']

In [11]:
kingdoms[-2:]

['Fungi', 'Animalia']

In [12]:
kingdoms[-1:-2]

[]

3.

In [13]:
appointments=['9:00', '10:30', '14:00', '15:00', '15:30']
appointments.append('16:30')
appointments

['9:00', '10:30', '14:00', '15:00', '15:30', '16:30']

In [14]:
appointment=['9:00', '10:30', '14:00', '15:00', '15:30']
appointment += ['16:30']
appointment


['9:00', '10:30', '14:00', '15:00', '15:30', '16:30']

4.

In [15]:
ids= [4353, 2314, 2956, 3382, 9362, 3900]
ids.remove(3382)
ids

[4353, 2314, 2956, 9362, 3900]

In [16]:
ids.index(9362)

3

In [17]:
ids.insert(4, 4499)
ids

[4353, 2314, 2956, 9362, 4499, 3900]

In [18]:
ids.append([5566, 1830])
ids

[4353, 2314, 2956, 9362, 4499, 3900, [5566, 1830]]

In [19]:
ids.reverse()
ids

[[5566, 1830], 3900, 4499, 9362, 2956, 2314, 4353]

5.

In [20]:
alkaline_earth_metals=[4, 8, 12, 20, 38, 56, 88]
alkaline_earth_metals

[4, 8, 12, 20, 38, 56, 88]

In [21]:
alkaline_earth_metals[5]

56

In [22]:
alkaline_earth_metals[-1]

88

In [23]:
count=0
for i in alkaline_earth_metals:
  count+=1
count

7

In [24]:
max(alkaline_earth_metals)

88

6.

In [25]:
temps=[25.2, 16.8, 31.4, 23.9, 28, 22.5, 19.6]

In [26]:
temps.sort()
temps

[16.8, 19.6, 22.5, 23.9, 25.2, 28, 31.4]

In [27]:
warm_temps=[]
cool_temps=[]
temps1=slice(2)
warm_temps=temps[temps1]
print(warm_temps)
temps2=slice(2,-1)
cool_temps=temps[temps2]
print(cool_temps)


[16.8, 19.6]
[22.5, 23.9, 25.2, 28]


In [28]:
temps_in_celsius=warm_temps+cool_temps
temps_in_celsius

[16.8, 19.6, 22.5, 23.9, 25.2, 28]

7.

In [29]:
def same_first_last(L):
  if L[0]==L[-1]:
    return True
  else:
    return False
print(same_first_last([3, 4, 2, 8, 3]))
print(same_first_last(['apple', 'banana', 'pear']))

True
False


8.

In [30]:
def is_longer(L1, L2):
  if len(L1)>len(L2):
    return True
  else:
    return False
print(is_longer([1, 2, 3], [4, 5]))
print(is_longer(['abcdef'], ['ab', 'cd', 'ef']))

True
False


9.

In [31]:
values = [0, 1, 2]
values[1] = values
values

[0, [...], 2]

10.

In [32]:
units=[['km', 'miles', 'league'], ['kg', 'pound', 'stone']]

In [33]:
units[0]

['km', 'miles', 'league']

In [34]:
units[-1]

['kg', 'pound', 'stone']

In [35]:
units[0][0]

'km'

In [36]:
units[1][0]

'kg'

In [37]:
units[0][1:]

['miles', 'league']

In [38]:
units[1][0:2]

['kg', 'pound']

11.

In [39]:
units[-2]

['km', 'miles', 'league']

In [40]:
units[-1]

['kg', 'pound', 'stone']

In [41]:
units[-2][-3]

'km'

In [42]:
units[-1][-3]

'kg'

In [43]:
units[-2][-2:]

['miles', 'league']

In [44]:
units[-1][:-1]

['kg', 'pound']

Bài tập chương 9

1.

In [45]:
celegans_phenotypes = ['Emb','Him', 'Unc', 'Lon', 'Dpy', 'Sma']
for phenotype in celegans_phenotypes:
  print(phenotype)

Emb
Him
Unc
Lon
Dpy
Sma


2.

In [46]:
half_lives=[87.74, 24110.0, 6537.0, 14.4, 376000.0]
for value in half_lives:
  print(value, end=' ')

87.74 24110.0 6537.0 14.4 376000.0 

3.

In [47]:
whales = [5, 4, 7, 3, 2, 3, 2, 6, 4, 2, 1, 7, 1, 3]
more_whales = []
for count in whales:
  more_whales.append(count + 1)
more_whales

[6, 5, 8, 4, 3, 4, 3, 7, 5, 3, 2, 8, 2, 4]

4.

In [48]:
alkaline_earth_metals = [[4, 9.012], [12, 24.305],
[20, 40.078], [38, 87.62],
[56, 137.327], [88, 226]]

In [49]:
for inner_list in alkaline_earth_metals:
  print(inner_list[0])
  print(inner_list[1])

4
9.012
12
24.305
20
40.078
38
87.62
56
137.327
88
226


In [50]:
number_and_weight = []
for inner_list in alkaline_earth_metals:
  number_and_weight.append(inner_list[0])
  number_and_weight.append(inner_list[1])
number_and_weight

[4, 9.012, 12, 24.305, 20, 40.078, 38, 87.62, 56, 137.327, 88, 226]

5.

In [51]:
def mystery_function(values):
  """ (list) -> list

Return a copy of the list, values, and the sublists it contains.
The top-level sublists have their elements reversed in the returned
list.

>>> mystery_function([[1, 2, 3], [4, 5, 6]])
[[3, 2, 1], [6, 5, 4]]
"""
  result = []
  for sublist in values:
    result.append([sublist[0]])
  for i in sublist[1:]:
    result[-1].insert(0, i)
  return result
mystery_function([[1, 2, 3], [4, 5, 6]])

[[1], [6, 5, 4]]

6.

In [52]:
text = ""
while text.lower() != "quit":
  text = input("Please enter a chemical formula (or 'quit' to exit): ")
  if text == "quit":
    print("...exiting program")
  elif text == "H2O":
    print("Water")
  elif text == "NH3":
    print("Ammonia")
  elif text == "CH4":
    print("Methane")
  else:
    print("Unknown compound")

Please enter a chemical formula (or 'quit' to exit): H2O
Water
Please enter a chemical formula (or 'quit' to exit): NH3
Ammonia
Please enter a chemical formula (or 'quit' to exit): quit
...exiting program


7.

In [53]:
country_populations = [1295, 23, 7, 3, 47, 21]
total = 0
for population in country_populations:
  total += population
total

1396

8.

In [54]:
import numpy as np
rat_1=np.random.randint(10,size=10)
rat_2=np.random.randint(10,size=10)
print(rat_1)
print(rat_2)
if rat_1[0] > rat_2[0]:
  print("Rat 1 weighed more than rat 2 on day 1.")
else:
  print("Rat 1 weighed less than rat 2 on day 1.")

[8 1 3 8 5 5 7 5 9 2]
[4 3 7 5 8 6 5 5 2 0]
Rat 1 weighed more than rat 2 on day 1.


In [55]:
print(rat_1)
print(rat_2)
if rat_1[0] > rat_2[0] and rat_1[-1] > rat_2[-1]:
  print("Rat 1 remained heavier than Rat 2.")
else:
  print("Rat 2 became heavier than Rat 1.")

[8 1 3 8 5 5 7 5 9 2]
[4 3 7 5 8 6 5 5 2 0]
Rat 1 remained heavier than Rat 2.


In [56]:
if rat_1[0] > rat_2[0]:
  if rat_1[-1] > rat_2[-1]:
    print("Rat 1 remained heavier than Rat 2.")
  else:
    print("Rat 2 became heavier than Rat 1.")
else:
  print("Rat 2 became heavier than Rat 1.")

Rat 1 remained heavier than Rat 2.


9.

In [57]:
for number in range(33, 50):
  print(number)

33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


10.

In [58]:
for number in range(10):
  print(10 - number, end=' ')

10 9 8 7 6 5 4 3 2 1 

11.

In [59]:
sum = 0
count = 0
for number in range(2,23):
  sum += number
  count += 1
average = sum / count
average

12.0

12.

In [60]:
def remove_neg(num_list):
  for i in num_list:
    if num_list[i] < 0:
      del num_list[i]
  print(num_list)
remove_neg([1, 2, 3, -3, 6, -1, -3, 1])

[1, 2, 3, 6, -3, 1]


13.

In [61]:
for width in range(1, 8):
  print('T' * width)

T
TT
TTT
TTTT
TTTTT
TTTTTT
TTTTTTT


14.

In [62]:
for width in range(1, 8):
  print(' '*(8 - width), 'T' * width)


        T
       TT
      TTT
     TTTT
    TTTTT
   TTTTTT
  TTTTTTT


15.

In [63]:
width = 1
while width < 8:
  print('T' * width)
  width += 1


T
TT
TTT
TTTT
TTTTT
TTTTTT
TTTTTTT


In [64]:
width = 1
while width < 8:
  print(' '*(8 - width), 'T' * width)
  width += 1

        T
       TT
      TTT
     TTTT
    TTTTT
   TTTTTT
  TTTTTTT
